/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scarman_loess_Loess */

#ifndef _Included_com_scarman_loess_Loess
#define _Included_com_scarman_loess_Loess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_scarman_loess_Loess
 * Method:    smooth
 * Signature: ([D[D[DDI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_scarman_loess_Loess_smooth
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
